---


    - name: Delete MySQL databases # depends on python-mysqldb (currently installed in various-packages)
      mysql_db: name={{item.1.db.name|default(item.0|replace('.','_'))}} state=absent
      with_items: drupal_sites_list
      when: drupal_reinstall is defined


    - name: Create MySQL databases # depends on python-mysqldb (currently installed in various-packages)
      mysql_db: name={{item.1.db.name|default(item.0|replace('.','_'))}} collation={{ drupal_database_collation }} state=present
      # debug: msg={{item}}
      with_items: drupal_sites_list
      register: db_created

    - name: Copy dump on VM
      copy: >
        src={{item.1.db.dump}}
        dest=/tmp/{{item.0}}.sql
      when: item.1.db.dump is defined
      with_items: drupal_sites_list


    - name: Import database dump
      mysql_db: name={{item.item.1.db.name}} state=import target=/tmp/{{item.item.0}}.sql
      when: item.item.1.db.dump is defined and item.changed
      with_items: db_created.results


    - name: Setup users for MySQL databases
      mysql_user: name={{ item.1.db.user }} password={{ item.1.db.password }} priv={{item.1.db.name|default(item.0|replace('.','_'))}}.*:ALL state=present
      with_items: drupal_sites_list
