---
    - name: Create MySQL databases # depends on python-mysqldb (currently installed in various-packages)
      mysql_db: name=kifi_emo collation=utf8_unicode_ci state=present

    - name: Setup users for MySQL databases
      mysql_user: name={{ db.name }} password={{ db.password }} priv={{ db.name }}.*:ALL state=present

# TODO: run drush site-install -y --db-url=mysql://{{ db.user }}:{{ db.password }}@localhost/{{ db.name }} but figure out a way to check whether or not the DB is there first



