---

    - name: Delete MySQL databases # depends on python-mysqldb (currently installed in various-packages)
      mysql_db: name={{db.name}} state=absent
      when: drupal_reinstall is defined

    - name: Create MySQL databases # depends on python-mysqldb (currently installed in various-packages)
      mysql_db: name={{db.name}} collation=utf8_unicode_ci state=present
      register: db_created

    - name: Copy dump on VM
      copy: >
        src={{db.dump}}
        dest=/tmp/{{site_name}}.sql
      when: db.dump is defined


    - name: Import database dump
      mysql_db: name={{db.name}} state=import target=/tmp/{{site_name}}.sql
      when: db.dump is defined and db_created.changed


    - name: Setup users for MySQL databases
      mysql_user: name={{ db.name }} password={{ db.password }} priv={{ db.name }}.*:ALL state=present
