---
    - name: Check out Drupal core from version control
      git: repo={{ drupal_git }}drupal.git dest=/srv/sites/{{site_name}}/www version={{ core }}

    - name: Check out Drupal modules from version control
      git: repo={{ drupal_git }}{{ item.name }}.git dest=/srv/sites/{{site_name}}/www/sites/all/modules/{{item.name}} version={{ item.version }}
      with_items: modules
      when: modules is defined

    - name: Check out Drupal themes from version control
      git: repo={{ drupal_git }}{{ item.name }}.git dest=/srv/sites/{{site_name}}/www/sites/all/themes/{{item.name}} version={{ item.version }}
      with_items: themes
      when: themes is defined

    - name: Check out local repositories
      git: repo={{ kifi_git }}{{ item.name }} dest=/srv/sites/{{site_name}}/www/{{item.dest}} version={{ item.version }}
      with_items: kifi_locals
      when: kifi_locals is defined

    # TODO: consider just moving to ACLs for shared config to get rid of all the permission issues
    - name: Set git to ignore permission changes
      command: /usr/bin/git --git-dir=/srv/sites/{{ site_name }}/www/.git --work-tree=/srv/sites/{{ site_name }}/www config core.filemode false

    - name: Set main directory permissions
      file: path=/srv/sites/{{ site_name }} owner=root group=git mode=0775 state=directory recurse=yes

    - name: Set files directory permissions
      file: path=/srv/sites/{{ site_name }}/www/sites/default/files owner=root group=www-data mode=2775 state=directory

    - name: Set sticky bit for all directories in site and execute for all
      shell: find /srv/sites/{{ site_name }} -type d -exec chmod +x,g+s {} \;

