---

      # TODO: account details to vars and passwords from vault or something
    - name: Install site with drush
      shell: >
          drush site-install {{install_profile}} --locale={{locale}} -y
          -r {{ drupal_sites_dir }}/{{ site_name }}/www/
          --db-url=mysql://{{ db.user }}:{{ db.password }}@localhost/{{ db.name }}
          --site-name={{site_name}}
          --account-mail={{site_admin_email}}
          --account-name=admin
          --account-pass=ofhooghEk3
      when: db_created.changed and db.dump is not defined

    - name: Copy files in place
      synchronize: src={{site_files}}/ dest={{drupal_multisite_directory}}/files delete=yes
      when: site_files is defined and db_created.changed and db.dump is defined


    - name: Copy config in place
      copy: src={{config_files}}/ dest={{drupal_config_directory}} force=yes
      when: config_files is defined and db_created.changed and db.dump is defined

    - name: Copy settings.php
      template: src=settings.php.j2 dest={{drupal_multisite_directory}}/settings.php
      when: db.dump is defined
